stages:
  - run_migration

execute_ansible:
  stage: run_migration
  tags:
    - shell  # Указываем тег твоего Shell-раннера, чтобы он перехватил задачу
  script:
    # Запускаем плейбук напрямую. Раннер сам возьмет SSH-ключ из ~/.ssh/gitlab-runner
    - ansible-playbook -i inventory.ini playbooks/migrate.yml --extra-vars "secret_encryption_key=$BACKUP_CRYPT_KEY"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
