---
- name: Подготовка репозитория хранения на целевом сервере
  file:
    path: "{{ target_destination_dir }}"
    state: directory
    mode: '0750'

- name: Шаг 1. Скачивание зашифрованных пакетов с исходного сервера на контроллер (мост)
  fetch:
    src: "{{ backup_local_dir }}/{{ item }}"
    dest: "/tmp/ansible_migration_buffer/"
    flat: yes
  delegate_to: "{{ groups['source_nodes'][0] }}"
  loop:
    - database_dump.sql.gz.enc
    - application_core.tar.gz.enc
    - manifest.sha256

- name: Шаг 2. Загрузка пакетов с контроллера на целевой сервер
  copy:
    src: "/tmp/ansible_migration_buffer/{{ item }}"
    dest: "{{ target_destination_dir }}/{{ item }}"
  loop:
    - database_dump.sql.gz.enc
    - application_core.tar.gz.enc
    - manifest.sha256

- name: Шаг 3. Очистка временного буфера на локальном контроллере
  file:
    path: "/tmp/ansible_migration_buffer/"
    state: absent
  delegate_to: localhost
  run_once: true
